### ISSUE TITLE
ADSBlol feed using adsb-feeder-image erroring out?

### ISSUE THREAD

**Issue by MrAirspace** [adsblol/feed#11]
Dear all,
I wanted to feed to ADSBlol so as per the instructions (https://www.adsb.lol/docs/hardware/adsb-equipment/) I ordered an AirNav RadarBox FlightStick and the pertaining antenna. Initially I tried the 'bare metal' command line approach but since I could not get it working I switched to the approach of using an adsb-feeder-image (https://adsb.im/howto). I followed all the steps but after the html dashboard page where I select the aggregators I want to feed to, the following page and after a couple of minutes the following html alert appears:
![what to do](https://github.com/adsblol/feed/assets/144953682/c936fb65-4062-4d9c-9d46-66dbde969650)

Is there any easy solution to this? I have to admit that Im unsure what it means. If for context purposes it is of any help, this is my hardware (so flight hardware as stated above, RPi is the Zero 2W. Kitchen environment only temporary location for testing - please ignore the kiwifruit)
![IMG_3601](https://github.com/adsblol/feed/assets/144953682/ac9530de-18db-4c98-b866-16a61b57f6ad)

If anybody has a solution to this, please let me know, greatly appreciated :) Thanks!
Sebastiaan.

**Comment by iakat** [comment]
Hi Sebastian,

For help with the adsb.im image, you can look at the adsb.lol zulip organisation 

https://adsblol.zulipchat.com/#narrow/stream/391168-adsb-feeder-image

This repo is for the docker feed toolkit or the bare metal install.
