### ISSUE TITLE
How to feed from my existing dump1090 setup

### ISSUE THREAD

**Issue by ggoodloff** [adsblol/feed#3]
Is there a way to configure my existing system that is already running a dump1090 setup to feed direct to adsb.lol without this container system. My setup is currently on a cloud Linux system that has atcp pipe to my pi via VPN and pulls from my pi via VPN because of Cox port blocking. It's loaded as a net-only dump1090 which thinks it's getting the data directly from the  SDR.

when I follow these instructions I get errors on the listen 30003 already in use

**Comment by iakat** [comment]
Hey, perhaps you can change your dump1090 port to a different value and expose a BEAST_IN port for the readsb container?
By setting `READSB_NET_BEAST_INPUT_PORT=port` in the docker-compose.yaml for the `readsb` service environment variables, and exposing the ports via `ports:`

Then if you configure your dump1090 to send beast to your port, you should be good & can take advantage of all the rest of the stack.

**Comment by ggoodloff** [comment]
It tells me that tcp4 0.0.0.0 port <anything> unable to bind; already in use

**Comment by ggoodloff** [comment]
This is what I get -- I have all these other services configured already in standalone feeds.... I'm just looking to feed into adsb-lol, but without a docker. I have had no luck getting a single one to run anything.

root@adsb1:/opt/adsblol/bin# adsblol-up
[ info] Removing old docker stack if it exists
[+] Running 8/8
 ⠿ Container adsblol        Removed                                                                                                                                                 0.1s
 ⠿ Container mlathub        Removed                                                                                                                                                 0.2s
 ⠿ Container tar1090        Removed                                                                                                                                                 0.1s
 ⠿ Container vnstat         Removed                                                                                                                                                 0.4s
 ⠿ Container watchtower     Removed                                                                                                                                                 0.5s
 ⠿ Container autoheal       Removed                                                                                                                                                 4.6s
 ⠿ Container readsb         Removed                                                                                                                                                 0.0s
 ⠿ Network adsblol_default  Removed                                                                                                                                                 0.1s
No stopped containers
[ info] Running docker-compose up with /opt/adsblol/cmdline.txt
[+] Running 7/9
 ⠿ Network adsblol_default                                           Created                                                                                                        0.2s
 ⠿ Container readsb                                                  Starting                                                                                                       1.3s
 ⠿ Container autoheal                                                Started                                                                                                        1.3s
 ⠿ Container watchtower                                              Started                                                                                                        1.2s
 ⠿ Container vnstat                                                  Started                                                                                                        0.6s
 ⠹ vnstat Published ports are discarded when using host network mode                                                                                                                0.0s
 ⠿ Container adsblol                                                 Created                                                                                                        0.1s
 ⠿ Container tar1090                                                 Created                                                                                                        0.1s
 ⠿ Container mlathub                                                 Created                                                                                                        0.0s
Error response from daemon: driver failed programming external connectivity on endpoint readsb (a938751a6786084d665040dfef510845df40adf2d06c8ac54d151a6dfb549c58): Error starting userland proxy: listen tcp4 0.0.0.0:30003: bind: address already in use

**Comment by iakat** [comment]
Apologies for not getting back to you here. Going to assume all is good. Feel free to reopen or get in touch on IRC if you need more help.
