### ISSUE TITLE
Please create a non-docker install

### ISSUE THREAD

**Issue by Mudary** [adsblol/feed#6]
Hi, I wish not to use docker on my linux machine. Please create a git clone webpage. The curl command does not include the adsblol-update or adsblol-up binaries.
Thank you

**Comment by iakat** [comment]
Hi @Mudary!

The README has a section on an adsbexchange-style feeder which is supposed to run next to an existing readsb installation: 
<img width="827" alt="image" src="https://user-images.githubusercontent.com/1695469/224179021-7ab81666-6d88-4345-8318-fa21dff5bb68.png">

Is this what you were looking for? The link "you can see here" has information about the script.

Indeed adsblol-update and adsblol-up commands are only for the docker based installation

**Comment by Mudary** [comment]
"Indeed adsblol-update and adsblol-up commands are only for the docker based installation"
Ok, I did not know that, will you be including these with the curl install.

**Comment by Mudary** [comment]
Question answered. Thank you Mudary

**Comment by iakat** [comment]
> "Indeed adsblol-update and adsblol-up commands are only for the docker based installation" Ok, I did not know that, will you be including these with the curl install.

I do not have any plans to do so, as I do not have the capacity to maintain it. I am maintaining the docker install as that is less time consuming for me. I welcome contributions and am open to giving you advice if this is something you or someone else is willing to work on.
